name: Hello World Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Also allows manual triggering from the Actions tab
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello Message
        run: echo "Hello, GitHub Actions World!"
        
      - name: Print Date
        run: echo "Today is $(date)"
        
      - name: Simple Environment Variable
        env:
          GREETING: "Hello from environment variables!"
        run: echo $GREETING